# Generated by Django 2.1.5 on 2019-05-06 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_remove_chair_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('group', models.CharField(choices=[('1', 'Grupo 0'), ('2', 'Grupo 1'), ('3', 'Grupo 2-3')], max_length=1)),
                ('score', models.IntegerField()),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('country', models.CharField(max_length=100)),
                ('image', models.ImageField(default='images/None/no-img.jpg', upload_to='images/')),
            ],
        ),
    ]
