# Generated by Django 2.1.5 on 2019-05-02 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chair',
            name='group',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
