# Generated by Django 2.1.5 on 2019-05-02 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_chair_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chair',
            name='group',
        ),
    ]
