# Generated by Django 2.1.5 on 2019-05-08 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='isofix',
            field=models.CharField(choices=[('si', 'si'), ('no', 'no')], default='si', max_length=2),
        ),
        migrations.AlterField(
            model_name='item',
            name='group',
            field=models.CharField(choices=[('0', 'Grupo 0'), ('0-1', 'Group 0-1'), ('1', 'Grupo 1'), ('2', 'Grupo 2-3')], max_length=3),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='images/None/no-img.jpg', upload_to='static/images/'),
        ),
    ]
